from . import views
from django.urls import path

urlpatterns = [
    path('',views.index),
    path('student_home',views.student_home,name='student_home'),
    path('coordinator_home',views.coordinator_home,name='coordinator_home'),
    path('guide_home',views.guide_home,name='guide_home'),
    path('student_mark',views.student_mark,name='student_mark'),
    path('student_progress',views.student_progress,name='student_progress'),
    path('register_project',views.register_project,name='register_project'),
    path('sign_up',views.sign_up,name='sign_up'),
    path('coordinator_announcement',views.coordinator_announcement,name='coordinator_announcement'),
    path('student_view_announcement',views.student_view_announcement,name='student_view_announcement'),
    path('student_sign_up',views.student_sign_up,name='student_sign_up'),
    path('coordinator_sign_up',views.coordinator_sign_up,name='coordinator_sign_up'),
    path('guide_sign_up',views.guide_sign_up,name='guide_sign_up'),
    path('student_register',views.student_register,name='student_register'),
    path('student_login',views.student_login,name='student_login'),
    path('logout_view',views.logout_view,name='logout_view'),
    path('coordinator_register',views.coordinator_register,name='coordinator_register'),
    path('coordinator_login',views.coordinator_login,name='coordinator_login'),
    path('coordinator_view_guide',views.coordinator_view_guide,name='coordinator_view_guide'),
    path('create_guide',views.create_guide,name='create_guide'),
    path('view_announcement',views.view_announcement,name='view_announcement'),
    path('guide_login',views.guide_login,name='guide_login'),
    path('review1',views.review1,name='review1'),
    path('view_team',views.view_team,name='view_team'),
    path('view_staff',views.view_staff,name='view_staff'),
    path('coordinator_delete_guide<str:pk>',views.coordinator_delete_guide,name='coordinator_delete_guide'),
    path('coordinator_delete_announcement/<str:pk>',views.coordinator_delete_announcement,name='coordinator_delete_announcement'),
    path('coordinator_assign_guide<str:pk>/',views.coordinator_assign_guide,name='coordinator_assign_guide'),
    path('guide_view_team',views.guide_view_team,name='guide_view_team'),
    path('student_chat',views.student_chat,name='student_chat'),
    path('send_chat',views.send_chat,name='send_chat'),
    path('guide_cha/<str:id>',views.guide_chat,name='guide_chat'),
    path('guide_send_chat',views.guide_send_chat,name='guide_send_chat'),
    path('student_review_mark<str:pk>',views.student_review_mark,name='student_review_mark'),
    path('guide_review_mark<str:pk>',views.guide_review_mark,name='guide_review_mark'),
    path('coordinator_calender',views.coordinator_calender,name='coordinator_calender'),
    path('view_resource_one',views.view_resource_one,name='view_resource_one'),
    path('view_calender',views.view_calender,name='view_calender'),
    path('submit_resource',views.submit_resource,name='submit_resource'),
    path('resource_form<str:pk>',views.resource_form,name='resource_form'),
    path('coordinator_review_one<str:pk>',views.coordinator_review_one,name='coordinator_review_one'),
    path('view_resource_two<str:pk>',views.view_resource_two,name='view_resource_two'),
    path('review_1/<str:pk>/<str:pk1>/<str:pk2>', views.review_1, name='review_1'),
    path('review_2/<str:pk>/<str:pk1>/<str:pk2>',views.review_2,name='review_2'),
    path('review_3/<str:pk>/<str:pk1>/<str:pk2>',views.review_3,name='review_3'),
    path('review_ese/<str:pk>/<str:pk1>/<str:pk2>',views.review_ese,name='review_ese'),
    path('review_guide/<str:pk>/<str:pk1>/<str:pk2>',views.review_guide,name='review_guide'),
    path('review_attendence/<str:pk>/<str:pk1>/<str:pk2>',views.review_attendence,name='review_attendence'),
    path('review_report/<str:pk>/<str:pk1>/<str:pk2>',views.review_report,name='review_report'),
    path('progress_of_team<str:pk>',views.progress_of_team,name='progress_of_team'),
    path('view_progress<str:pk>',views.view_progress,name='view_progress'),
    path('view_resources<str:pk>',views.view_resources,name='view_resources'),
    path('student_review_mark_one',views.student_review_mark_one,name='student_review_mark_one'),
    path('view_reviews',views.view_reviews,name='view_reviews'),
    path('guide_review<str:pk>',views.guide_review,name='guide_review'),
    path('coordinator_review',views.coordinator_review,name='coordinator_review'),

]