# Generated by Django 5.0.4 on 2024-05-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_projectannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectannouncement',
            name='now_date',
            field=models.DateField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='projectannouncement',
            name='date',
            field=models.DateField(max_length=128, null=True),
        ),
    ]
