# Generated by Django 5.0.4 on 2024-05-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projectannouncement_now_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerproject',
            name='assign',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registerproject',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.guidereg'),
        ),
    ]
