# Generated by Django 5.0.4 on 2024-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registerproject_assign_registerproject_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='code',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
