# Generated by Django 5.0.4 on 2024-05-04 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chat_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='code',
        ),
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.registerproject'),
            preserve_default=False,
        ),
    ]
