# Generated by Django 5.0.4 on 2024-05-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_calender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_link', models.CharField(max_length=1000)),
                ('calender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calender')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
