# Generated by Django 5.0.4 on 2024-05-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=128)),
                ('memberId', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerproject')),
            ],
        ),
        migrations.CreateModel(
            name='EndSemEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('demo', models.IntegerField()),
                ('viva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=128)),
                ('memberId', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerproject')),
            ],
        ),
        migrations.CreateModel(
            name='GuideMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_std_mini_pro', models.IntegerField()),
                ('know_invol_work', models.IntegerField()),
                ('total', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=128)),
                ('memberId', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerproject')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=128)),
                ('memberId', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerproject')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_pro', models.IntegerField()),
                ('liter_review', models.IntegerField()),
                ('obj_des_meth', models.IntegerField()),
                ('total', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=128)),
                ('memberId', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerproject')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_com_demo', models.IntegerField()),
                ('total', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=128)),
                ('memberId', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerproject')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_meth_algo', models.IntegerField()),
                ('pro_implement', models.IntegerField()),
                ('viva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=128)),
                ('memberId', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerproject')),
            ],
        ),
    ]
